CREATE DATABASE CarTrackerDB;

USE CarTrackerDB;

CREATE TABLE User (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Role VARCHAR(255) DEFAULT NULL,
    Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
